### ISSUE TITLE
TypeError: Unable to set property 'value' of undefined or null reference

### ISSUE THREAD

**Issue by assafv** [bcbi/Canvas-React-Node-MySQL#3]
https://github.com/bcbi/Canvas-React-Node-MySQL/blob/81624ed7c070eab6dec988d218b2fdf518e90e34/client/src/components/Search.js#L32

**Comment by DilumAluthge** [comment]
This package is deprecated and is no longer maintained. Therefore, I am closing this issue.

Please see [https://github.com/bcbi/code_style_guide](https://github.com/bcbi/code_style_guide) for information on JavaScript development at BCBI.
